version: '3'

networks:
  menuorders-net:


services:
  backend:
    image: docker.io/georgesigoiu/menu-orders:1.1.0
    restart: always
    ports:
      - "7900:7900"
    networks:
      - menuorders-net
